-- ALL SEED DATA WAS GENERATED WITH AI

INSERT INTO saved_posts (user_id, post_id)
VALUES
    ((SELECT id FROM users WHERE username = 'mossyrock'), (SELECT id FROM posts WHERE title = 'Small apartment DIY projects that do not require a landlord''s permission')),
    ((SELECT id FROM users WHERE username = 'paperplane'), (SELECT id FROM posts WHERE title = 'A book that completely changed how you read afterward')),
    ((SELECT id FROM users WHERE username = 'pixelpanda'), (SELECT id FROM posts WHERE title = 'That viral kitchen gadget everyone is buying is mostly a single-use plastic paperweight')),
    ((SELECT id FROM users WHERE username = 'sleeplessdev'), (SELECT id FROM posts WHERE title = 'A popular npm package pushed a breaking change as a patch version last night')),
    ((SELECT id FROM users WHERE username = 'sleeplessdev'), (SELECT id FROM posts WHERE title = 'How do you get comfortable sharing unfinished or rough work?')),
    ((SELECT id FROM users WHERE username = 'moonrabbit'), (SELECT id FROM posts WHERE title = 'New exoplanet survey results published this week')),
    ((SELECT id FROM users WHERE username = 'retrograde'), (SELECT id FROM posts WHERE title = 'Solo travel versus traveling with others, which do you actually prefer?')),
    ((SELECT id FROM users WHERE username = 'paperplane'), (SELECT id FROM posts WHERE title = 'An underdog performance this season that genuinely surprised you')),
    ((SELECT id FROM users WHERE username = 'codewanderer'), (SELECT id FROM posts WHERE title = 'How strict should code review comments be for a two person team?')),
    ((SELECT id FROM users WHERE username = 'sunnydays'), (SELECT id FROM posts WHERE title = 'What is something you were confidently wrong about for way too long?')),
    ((SELECT id FROM users WHERE username = 'codewanderer'), (SELECT id FROM posts WHERE title = 'Major trade finalized this morning, reactions are split')),
    ((SELECT id FROM users WHERE username = 'wildfern'), (SELECT id FROM posts WHERE title = 'Is it worth switching to a password manager at this point, or overkill?')),
    ((SELECT id FROM users WHERE username = 'paperplane'), (SELECT id FROM posts WHERE title = 'How do you actually discover new music these days?')),
    ((SELECT id FROM users WHERE username = 'wanderlust'), (SELECT id FROM posts WHERE title = 'A common houseplant is more toxic to cats than most people realize')),
    ((SELECT id FROM users WHERE username = 'frogboy'), (SELECT id FROM posts WHERE title = 'Old charging cables can quietly start a fire, worth checking yours')),
    ((SELECT id FROM users WHERE username = 'sleeplessdev'), (SELECT id FROM posts WHERE title = 'How do you stay motivated during the "boring middle" of a fitness routine?')),
    ((SELECT id FROM users WHERE username = 'stacktrace'), (SELECT id FROM posts WHERE title = 'What is a scientific fact that broke your brain a little when you first learned it?')),
    ((SELECT id FROM users WHERE username = 'analogkid'), (SELECT id FROM posts WHERE title = 'Tried a running plan aimed at complete beginners, six weeks in')),
    ((SELECT id FROM users WHERE username = 'stacktrace'), (SELECT id FROM posts WHERE title = 'Games where the soundtrack carried the whole experience for you')),
    ((SELECT id FROM users WHERE username = 'crispytoast'), (SELECT id FROM posts WHERE title = 'The most underrated city you''ve visited that nobody talks about')),
    ((SELECT id FROM users WHERE username = 'coffeeaddict'), (SELECT id FROM posts WHERE title = 'A supporting actor performance that stole the whole movie for you')),
    ((SELECT id FROM users WHERE username = 'moonrabbit'), (SELECT id FROM posts WHERE title = 'The most underrated city you''ve visited that nobody talks about')),
    ((SELECT id FROM users WHERE username = 'wildfern'), (SELECT id FROM posts WHERE title = 'Best way to handle a long layover without a visa for the country?')),
    ((SELECT id FROM users WHERE username = 'frogboy'), (SELECT id FROM posts WHERE title = 'A rivalry game that lived up to the hype for once')),
    ((SELECT id FROM users WHERE username = 'moonrabbit'), (SELECT id FROM posts WHERE title = 'How do you organize a music library that has grown out of control?')),
    ((SELECT id FROM users WHERE username = 'neonriver'), (SELECT id FROM posts WHERE title = 'Heads up, a lot of train operators in Europe are on strike this month')),
    ((SELECT id FROM users WHERE username = 'neonriver'), (SELECT id FROM posts WHERE title = 'Went back to a 2011 RPG after years away, holds up better than expected')),
    ((SELECT id FROM users WHERE username = 'bughunter'), (SELECT id FROM posts WHERE title = 'What is a small purchase under twenty dollars that improved your daily life?')),
    ((SELECT id FROM users WHERE username = 'paperplane'), (SELECT id FROM posts WHERE title = 'Finished the new roguelike everyone was talking about, quick thoughts')),
    ((SELECT id FROM users WHERE username = 'frogboy'), (SELECT id FROM posts WHERE title = 'Small apartment DIY projects that do not require a landlord''s permission')),
    ((SELECT id FROM users WHERE username = 'teatime'), (SELECT id FROM posts WHERE title = 'Older cat suddenly more vocal at night, anyone dealt with this?')),
    ((SELECT id FROM users WHERE username = 'teatime'), (SELECT id FROM posts WHERE title = 'That viral kitchen gadget everyone is buying is mostly a single-use plastic paperweight')),
    ((SELECT id FROM users WHERE username = 'paperplane'), (SELECT id FROM posts WHERE title = 'How do you warm up properly without it eating half your workout time?')),
    ((SELECT id FROM users WHERE username = 'kiwibird'), (SELECT id FROM posts WHERE title = 'Solo travel versus traveling with others, which do you actually prefer?')),
    ((SELECT id FROM users WHERE username = 'mossyrock'), (SELECT id FROM posts WHERE title = 'What is the one kitchen tool you didn''t think you needed until you had it?')),
    ((SELECT id FROM users WHERE username = 'codewanderer'), (SELECT id FROM posts WHERE title = 'New exoplanet survey results published this week')),
    ((SELECT id FROM users WHERE username = 'orbitingmars'), (SELECT id FROM posts WHERE title = 'Switched our team from REST to GraphQL, six months later thoughts')),
    ((SELECT id FROM users WHERE username = 'retrograde'), (SELECT id FROM posts WHERE title = 'Pets who have very specific and nonnegotiable opinions about their food bowl')),
    ((SELECT id FROM users WHERE username = 'neonriver'), (SELECT id FROM posts WHERE title = 'Looking for nonfiction that reads like a novel')),
    ((SELECT id FROM users WHERE username = 'cloudchaser'), (SELECT id FROM posts WHERE title = 'How do you name boolean variables so they read cleanly in conditionals?')),
    ((SELECT id FROM users WHERE username = 'moonrabbit'), (SELECT id FROM posts WHERE title = 'Is it worth switching to a password manager at this point, or overkill?')),
    ((SELECT id FROM users WHERE username = 'mossyrock'), (SELECT id FROM posts WHERE title = 'A film that got better on rewatch for you')),
    ((SELECT id FROM users WHERE username = 'orbitingmars'), (SELECT id FROM posts WHERE title = 'What is a small purchase under twenty dollars that improved your daily life?')),
    ((SELECT id FROM users WHERE username = 'hexadecimal'), (SELECT id FROM posts WHERE title = 'Long-rumored remaster finally gets an official trailer')),
    ((SELECT id FROM users WHERE username = 'teatime'), (SELECT id FROM posts WHERE title = 'Solo travel versus traveling with others, which do you actually prefer?')),
    ((SELECT id FROM users WHERE username = 'retrograde'), (SELECT id FROM posts WHERE title = 'Old charging cables can quietly start a fire, worth checking yours')),
    ((SELECT id FROM users WHERE username = 'hexadecimal'), (SELECT id FROM posts WHERE title = 'A common houseplant is more toxic to cats than most people realize')),
    ((SELECT id FROM users WHERE username = 'orbitingmars'), (SELECT id FROM posts WHERE title = 'A popular npm package pushed a breaking change as a patch version last night')),
    ((SELECT id FROM users WHERE username = 'frogboy'), (SELECT id FROM posts WHERE title = 'How do you get comfortable sharing unfinished or rough work?')),
    ((SELECT id FROM users WHERE username = 'orbitingmars'), (SELECT id FROM posts WHERE title = 'Do you actually use the notes app on your phone, or does everything just sit there forgotten?')),
    ((SELECT id FROM users WHERE username = 'frogboy'), (SELECT id FROM posts WHERE title = 'Best way to handle a long layover without a visa for the country?')),
    ((SELECT id FROM users WHERE username = 'sunnydays'), (SELECT id FROM posts WHERE title = 'A popular npm package pushed a breaking change as a patch version last night')),
    ((SELECT id FROM users WHERE username = 'slowinternet'), (SELECT id FROM posts WHERE title = 'Read a debut novel that everyone online seemed to love, mixed on it myself')),
    ((SELECT id FROM users WHERE username = 'nightowl'), (SELECT id FROM posts WHERE title = 'How strict should code review comments be for a two person team?')),
    ((SELECT id FROM users WHERE username = 'mossyrock'), (SELECT id FROM posts WHERE title = 'Tried a running plan aimed at complete beginners, six weeks in')),
    ((SELECT id FROM users WHERE username = 'hexadecimal'), (SELECT id FROM posts WHERE title = 'Editing style feedback, am I overdoing the contrast?')),
    ((SELECT id FROM users WHERE username = 'wanderlust'), (SELECT id FROM posts WHERE title = 'How long did it take your rescue dog to actually settle in?')),
    ((SELECT id FROM users WHERE username = 'analogkid'), (SELECT id FROM posts WHERE title = 'How do you actually discover new music these days?')),
    ((SELECT id FROM users WHERE username = 'neonriver'), (SELECT id FROM posts WHERE title = 'How do you get into following a sport as an adult with no background in it?')),
    ((SELECT id FROM users WHERE username = 'neonriver'), (SELECT id FROM posts WHERE title = 'Tried an e-ink tablet for note-taking, here is how it went after three months')),
    ((SELECT id FROM users WHERE username = 'crispytoast'), (SELECT id FROM posts WHERE title = 'How long did it take your rescue dog to actually settle in?')),
    ((SELECT id FROM users WHERE username = 'hexadecimal'), (SELECT id FROM posts WHERE title = 'First time hearing this genre live, did not expect to enjoy it that much')),
    ((SELECT id FROM users WHERE username = 'wanderlust'), (SELECT id FROM posts WHERE title = 'A popular npm package pushed a breaking change as a patch version last night')),
    ((SELECT id FROM users WHERE username = 'wanderlust'), (SELECT id FROM posts WHERE title = 'Long-rumored remaster finally gets an official trailer')),
    ((SELECT id FROM users WHERE username = 'alexm'), (SELECT id FROM posts WHERE title = 'Took an online course from an artist I have followed for years, worth the price')),
    ((SELECT id FROM users WHERE username = 'frogboy'), (SELECT id FROM posts WHERE title = 'Tried an e-ink tablet for note-taking, here is how it went after three months')),
    ((SELECT id FROM users WHERE username = 'cloudchaser'), (SELECT id FROM posts WHERE title = 'A rivalry game that lived up to the hype for once')),
    ((SELECT id FROM users WHERE username = 'crispytoast'), (SELECT id FROM posts WHERE title = 'Do rest days actually need to be fully sedentary, or does light movement help?')),
    ((SELECT id FROM users WHERE username = 'analogkid'), (SELECT id FROM posts WHERE title = 'Do you finish pieces you''ve fallen out of love with, or abandon them?')),
    ((SELECT id FROM users WHERE username = 'neonriver'), (SELECT id FROM posts WHERE title = 'Do you finish pieces you''ve fallen out of love with, or abandon them?')),
    ((SELECT id FROM users WHERE username = 'sunnydays'), (SELECT id FROM posts WHERE title = 'Albums that work best as a single uninterrupted listen')),
    ((SELECT id FROM users WHERE username = 'mossyrock'), (SELECT id FROM posts WHERE title = 'Do you comment your code more or less than you used to?')),
    ((SELECT id FROM users WHERE username = 'cloudchaser'), (SELECT id FROM posts WHERE title = 'Games where the soundtrack carried the whole experience for you')),
    ((SELECT id FROM users WHERE username = 'sleeplessdev'), (SELECT id FROM posts WHERE title = 'New exoplanet survey results published this week')),
    ((SELECT id FROM users WHERE username = 'moonrabbit'), (SELECT id FROM posts WHERE title = 'Do you actually use the notes app on your phone, or does everything just sit there forgotten?')),
    ((SELECT id FROM users WHERE username = 'moonrabbit'), (SELECT id FROM posts WHERE title = 'Solo travel versus traveling with others, which do you actually prefer?')),
    ((SELECT id FROM users WHERE username = 'frogboy'), (SELECT id FROM posts WHERE title = 'Vinyl collectors, how do you decide what actually earns a physical copy?')),
    ((SELECT id FROM users WHERE username = 'bytebandit'), (SELECT id FROM posts WHERE title = 'Tried a running plan aimed at complete beginners, six weeks in')),
    ((SELECT id FROM users WHERE username = 'moonrabbit'), (SELECT id FROM posts WHERE title = 'Major trade finalized this morning, reactions are split')),
    ((SELECT id FROM users WHERE username = 'wanderlust'), (SELECT id FROM posts WHERE title = 'Traditional media versus digital, do you have a strong preference?')),
    ((SELECT id FROM users WHERE username = 'retrograde'), (SELECT id FROM posts WHERE title = 'Older cat suddenly more vocal at night, anyone dealt with this?')),
    ((SELECT id FROM users WHERE username = 'teatime'), (SELECT id FROM posts WHERE title = 'Tried a viral pasta recipe from a video, verdict below')),
    ((SELECT id FROM users WHERE username = 'neonriver'), (SELECT id FROM posts WHERE title = 'Popular framework just announced a major version with a new compiler')),
    ((SELECT id FROM users WHERE username = 'neonriver'), (SELECT id FROM posts WHERE title = 'Tried a running plan aimed at complete beginners, six weeks in')),
    ((SELECT id FROM users WHERE username = 'frogboy'), (SELECT id FROM posts WHERE title = 'How do you organize a music library that has grown out of control?')),
    ((SELECT id FROM users WHERE username = 'teatime'), (SELECT id FROM posts WHERE title = 'Looking for a movie night pick that works for a mixed group of tastes')),
    ((SELECT id FROM users WHERE username = 'wanderlust'), (SELECT id FROM posts WHERE title = 'The most inexplicable thing your pet has ever done')),
    ((SELECT id FROM users WHERE username = 'frogboy'), (SELECT id FROM posts WHERE title = 'How do you organize thousands of photos without losing your mind?')),
    ((SELECT id FROM users WHERE username = 'coffeeaddict'), (SELECT id FROM posts WHERE title = 'What is a coding habit you picked up that you wish you learned earlier?')),
    ((SELECT id FROM users WHERE username = 'alexm'), (SELECT id FROM posts WHERE title = 'Switched our team from REST to GraphQL, six months later thoughts')),
    ((SELECT id FROM users WHERE username = 'retrograde'), (SELECT id FROM posts WHERE title = 'Is it worth switching to a password manager at this point, or overkill?')),
    ((SELECT id FROM users WHERE username = 'slowinternet'), (SELECT id FROM posts WHERE title = 'Why do we yawn, and why is it so contagious?')),
    ((SELECT id FROM users WHERE username = 'bytebandit'), (SELECT id FROM posts WHERE title = 'Long-rumored remaster finally gets an official trailer')),
    ((SELECT id FROM users WHERE username = 'wildfern'), (SELECT id FROM posts WHERE title = 'Finished the new roguelike everyone was talking about, quick thoughts')),
    ((SELECT id FROM users WHERE username = 'sunnydays'), (SELECT id FROM posts WHERE title = 'Home gym setups on a tight budget, what was actually worth buying?')),
    ((SELECT id FROM users WHERE username = 'slowinternet'), (SELECT id FROM posts WHERE title = 'Is anyone else exhausted by how many "AI" features are being bolted onto everything?')),
    ((SELECT id FROM users WHERE username = 'alexm'), (SELECT id FROM posts WHERE title = 'Looking for nonfiction that reads like a novel')),
    ((SELECT id FROM users WHERE username = 'kiwibird'), (SELECT id FROM posts WHERE title = 'Games you kept playing well past the credits rolling')),
    ((SELECT id FROM users WHERE username = 'coffeeaddict'), (SELECT id FROM posts WHERE title = 'A popular npm package pushed a breaking change as a patch version last night')),
    ((SELECT id FROM users WHERE username = 'cloudchaser'), (SELECT id FROM posts WHERE title = 'Do rest days actually need to be fully sedentary, or does light movement help?')),
    ((SELECT id FROM users WHERE username = 'bluecomet'), (SELECT id FROM posts WHERE title = 'What is something you were confidently wrong about for way too long?')),
    ((SELECT id FROM users WHERE username = 'orbitingmars'), (SELECT id FROM posts WHERE title = 'Tried shooting an entire wedding on a rented lens I had never used before')),
    ((SELECT id FROM users WHERE username = 'moonrabbit'), (SELECT id FROM posts WHERE title = 'A common houseplant is more toxic to cats than most people realize')),
    ((SELECT id FROM users WHERE username = 'orbitingmars'), (SELECT id FROM posts WHERE title = 'Home gym setups on a tight budget, what was actually worth buying?')),
    ((SELECT id FROM users WHERE username = 'coffeeaddict'), (SELECT id FROM posts WHERE title = 'How do you stay motivated during the "boring middle" of a fitness routine?')),
    ((SELECT id FROM users WHERE username = 'orbitingmars'), (SELECT id FROM posts WHERE title = 'Games you kept playing well past the credits rolling')),
    ((SELECT id FROM users WHERE username = 'coffeeaddict'), (SELECT id FROM posts WHERE title = 'How far in advance do you actually book flights for the best price?')),
    ((SELECT id FROM users WHERE username = 'neonriver'), (SELECT id FROM posts WHERE title = 'Finished the new roguelike everyone was talking about, quick thoughts')),
    ((SELECT id FROM users WHERE username = 'neonriver'), (SELECT id FROM posts WHERE title = 'What is a small daily habit that quietly improved your life?')),
    ((SELECT id FROM users WHERE username = 'moonrabbit'), (SELECT id FROM posts WHERE title = 'Is there a food you loved as a kid that you cannot stand now?')),
    ((SELECT id FROM users WHERE username = 'neonriver'), (SELECT id FROM posts WHERE title = 'How long did it take your rescue dog to actually settle in?')),
    ((SELECT id FROM users WHERE username = 'kiwibird'), (SELECT id FROM posts WHERE title = 'Best way to handle a long layover without a visa for the country?')),
    ((SELECT id FROM users WHERE username = 'codewanderer'), (SELECT id FROM posts WHERE title = 'First time hearing this genre live, did not expect to enjoy it that much')),
    ((SELECT id FROM users WHERE username = 'analogkid'), (SELECT id FROM posts WHERE title = 'Best budget headset for competitive online games?')),
    ((SELECT id FROM users WHERE username = 'codewanderer'), (SELECT id FROM posts WHERE title = 'What is a small purchase under twenty dollars that improved your daily life?')),
    ((SELECT id FROM users WHERE username = 'wildfern'), (SELECT id FROM posts WHERE title = 'Looking for nonfiction that reads like a novel')),
    ((SELECT id FROM users WHERE username = 'frogboy'), (SELECT id FROM posts WHERE title = 'Reminder to check your router firmware before the long weekend')),
    ((SELECT id FROM users WHERE username = 'hexadecimal'), (SELECT id FROM posts WHERE title = 'Do you finish books you are not enjoying, or abandon them?')),
    ((SELECT id FROM users WHERE username = 'analogkid'), (SELECT id FROM posts WHERE title = 'A supporting actor performance that stole the whole movie for you')),
    ((SELECT id FROM users WHERE username = 'frogboy'), (SELECT id FROM posts WHERE title = 'Spent a weekend rewriting a script in a language I barely know, worth it')),
    ((SELECT id FROM users WHERE username = 'sleeplessdev'), (SELECT id FROM posts WHERE title = 'Caught a small venue show last night, best live sound I''ve heard all year')),
    ((SELECT id FROM users WHERE username = 'kiwibird'), (SELECT id FROM posts WHERE title = 'Went back to a 2011 RPG after years away, holds up better than expected')),
    ((SELECT id FROM users WHERE username = 'moonrabbit'), (SELECT id FROM posts WHERE title = 'Went back to a 2011 RPG after years away, holds up better than expected')),
    ((SELECT id FROM users WHERE username = 'bytebandit'), (SELECT id FROM posts WHERE title = 'Anyone else keep a running list of restaurants they mean to try?')),
    ((SELECT id FROM users WHERE username = 'nordicfox'), (SELECT id FROM posts WHERE title = 'Do you actually use the notes app on your phone, or does everything just sit there forgotten?')),
    ((SELECT id FROM users WHERE username = 'retrograde'), (SELECT id FROM posts WHERE title = 'Researchers report a new material that conducts electricity at higher temperatures than previous records')),
    ((SELECT id FROM users WHERE username = 'wanderlust'), (SELECT id FROM posts WHERE title = 'Do you actually use the notes app on your phone, or does everything just sit there forgotten?')),
    ((SELECT id FROM users WHERE username = 'frogboy'), (SELECT id FROM posts WHERE title = 'Director confirms sequel is officially in early development')),
    ((SELECT id FROM users WHERE username = 'mossyrock'), (SELECT id FROM posts WHERE title = 'How do you deal with comparing your progress to people who started around the same time as you?')),
    ((SELECT id FROM users WHERE username = 'alexm'), (SELECT id FROM posts WHERE title = 'Games you kept playing well past the credits rolling')),
    ((SELECT id FROM users WHERE username = 'wildfern'), (SELECT id FROM posts WHERE title = 'Read a debut novel that everyone online seemed to love, mixed on it myself')),
    ((SELECT id FROM users WHERE username = 'stacktrace'), (SELECT id FROM posts WHERE title = 'Albums that work best as a single uninterrupted listen')),
    ((SELECT id FROM users WHERE username = 'teatime'), (SELECT id FROM posts WHERE title = 'How long did it take your rescue dog to actually settle in?'));